DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'td_writer') THEN
    CREATE ROLE td_writer;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'td_app') THEN
    CREATE USER td_app WITH ENCRYPTED PASSWORD '<SENHA_FORTE>' LOGIN;
  END IF;
END $$;

DO $$
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO td_writer', current_database());
END $$;

GRANT USAGE, CREATE ON SCHEMA public TO td_writer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO td_writer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO td_writer;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO td_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO td_writer;

GRANT td_writer TO td_app;
