# =============================================
# TechDengue Dashboard - Dockerfile
# Multi-stage build for optimized production image
# =============================================

# Stage 1: Dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set environment variables for build
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Build-time environment variables (NEXT_PUBLIC_* are baked at build time)
# ===== APP =====
ARG NEXT_PUBLIC_APP_NAME="TechDengue Dashboard"
ARG NEXT_PUBLIC_APP_VERSION="1.0.0"
ARG NEXT_PUBLIC_APP_ENV="production"

# ===== API TECHDENGUE =====
ARG NEXT_PUBLIC_API_BASE_URL="https://api.sistematechdengue.com/api/v1"
ARG NEXT_PUBLIC_API_TIMEOUT="30000"
ARG NEXT_PUBLIC_API_RETRY_ATTEMPTS="3"
ARG NEXT_PUBLIC_API_ACCESS_TOKEN=""
ARG NEXT_PUBLIC_API_SERVICE_EMAIL=""
ARG NEXT_PUBLIC_API_SERVICE_PASSWORD=""

# ===== MAPBOX =====
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN="pk.eyJ1IjoiYWVyb2Nsb3VkIiwiYSI6ImNtaWVvZzVqeTA1aXozZXBzMXNxZWo0ZnEifQ.KwMXCX8GBnQKaTaea2CWkA"
ARG NEXT_PUBLIC_MAPBOX_STYLE="mapbox://styles/mapbox/light-v11"
ARG NEXT_PUBLIC_MAPBOX_DEFAULT_ZOOM="5"
ARG NEXT_PUBLIC_MAPBOX_DEFAULT_CENTER_LAT="-16.6869"
ARG NEXT_PUBLIC_MAPBOX_DEFAULT_CENTER_LNG="-49.2646"

# ===== OPENWEATHER =====
ARG NEXT_PUBLIC_OPENWEATHER_API_KEY="0d993e8b059135c9548085a50ff48f68"
ARG NEXT_PUBLIC_OPENWEATHER_BASE_URL="https://api.openweathermap.org/data/2.5"
ARG NEXT_PUBLIC_OPENWEATHER_UNITS="metric"

# ===== ANALYTICS =====
ARG NEXT_PUBLIC_SENTRY_DSN="https://401ae6d084e41e4a8e9f0fd3d71710cc@o4510502722142208.ingest.us.sentry.io/4510502738460672"
ARG NEXT_PUBLIC_POSTHOG_KEY="phc_dWOtEa6gskrHxGRhVjzAxnqymigaEDpxwVBVcTAnWLY"
ARG NEXT_PUBLIC_POSTHOG_HOST="https://app.posthog.com"
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID="G-YYSPNFMHSW"

# ===== FEATURE FLAGS =====
ARG NEXT_PUBLIC_ENABLE_DARK_MODE="true"
ARG NEXT_PUBLIC_ENABLE_WEATHER_CORRELATION="true"
ARG NEXT_PUBLIC_ENABLE_PREDICTIVE_ANALYTICS="false"
ARG NEXT_PUBLIC_ENABLE_EXPORT_PDF="true"
ARG NEXT_PUBLIC_ENABLE_EXPORT_EXCEL="true"

# ===== DEBUG =====
ARG NEXT_PUBLIC_MOCK_API="false"
ARG NEXT_PUBLIC_DEBUG_MODE="false"
ARG NEXT_PUBLIC_LOG_LEVEL="warn"

# Set environment variables from ARGs
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION
ENV NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_TIMEOUT=$NEXT_PUBLIC_API_TIMEOUT
ENV NEXT_PUBLIC_API_RETRY_ATTEMPTS=$NEXT_PUBLIC_API_RETRY_ATTEMPTS
ENV NEXT_PUBLIC_API_ACCESS_TOKEN=$NEXT_PUBLIC_API_ACCESS_TOKEN
ENV NEXT_PUBLIC_API_SERVICE_EMAIL=$NEXT_PUBLIC_API_SERVICE_EMAIL
ENV NEXT_PUBLIC_API_SERVICE_PASSWORD=$NEXT_PUBLIC_API_SERVICE_PASSWORD
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=$NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ENV NEXT_PUBLIC_MAPBOX_STYLE=$NEXT_PUBLIC_MAPBOX_STYLE
ENV NEXT_PUBLIC_MAPBOX_DEFAULT_ZOOM=$NEXT_PUBLIC_MAPBOX_DEFAULT_ZOOM
ENV NEXT_PUBLIC_MAPBOX_DEFAULT_CENTER_LAT=$NEXT_PUBLIC_MAPBOX_DEFAULT_CENTER_LAT
ENV NEXT_PUBLIC_MAPBOX_DEFAULT_CENTER_LNG=$NEXT_PUBLIC_MAPBOX_DEFAULT_CENTER_LNG
ENV NEXT_PUBLIC_OPENWEATHER_API_KEY=$NEXT_PUBLIC_OPENWEATHER_API_KEY
ENV NEXT_PUBLIC_OPENWEATHER_BASE_URL=$NEXT_PUBLIC_OPENWEATHER_BASE_URL
ENV NEXT_PUBLIC_OPENWEATHER_UNITS=$NEXT_PUBLIC_OPENWEATHER_UNITS
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY
ENV NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST
ENV NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID
ENV NEXT_PUBLIC_ENABLE_DARK_MODE=$NEXT_PUBLIC_ENABLE_DARK_MODE
ENV NEXT_PUBLIC_ENABLE_WEATHER_CORRELATION=$NEXT_PUBLIC_ENABLE_WEATHER_CORRELATION
ENV NEXT_PUBLIC_ENABLE_PREDICTIVE_ANALYTICS=$NEXT_PUBLIC_ENABLE_PREDICTIVE_ANALYTICS
ENV NEXT_PUBLIC_ENABLE_EXPORT_PDF=$NEXT_PUBLIC_ENABLE_EXPORT_PDF
ENV NEXT_PUBLIC_ENABLE_EXPORT_EXCEL=$NEXT_PUBLIC_ENABLE_EXPORT_EXCEL
ENV NEXT_PUBLIC_MOCK_API=$NEXT_PUBLIC_MOCK_API
ENV NEXT_PUBLIC_DEBUG_MODE=$NEXT_PUBLIC_DEBUG_MODE
ENV NEXT_PUBLIC_LOG_LEVEL=$NEXT_PUBLIC_LOG_LEVEL

# Build the application
RUN pnpm build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Set correct permissions
RUN chown -R nextjs:nodejs /app

# Switch to non-root user
USER nextjs

# Expose port
EXPOSE 3000

# Set hostname
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

# Start the application
CMD ["node", "server.js"]
